version: '3.8'
services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    networks:
      - django-dev
  db:
    image: mariadb:10.5
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "django"
      # MYSQL_USER: "django"
      # MYSQL_PASSWORD: "${MYSQL_USER_PASSWORD}"
    networks:
      - django-dev
    restart: always

networks:
  django-dev:
    driver: bridge